var num1 = 10;
var num2 = 20;
console.log("num1 的值为 " + num1);
console.log("num2 的值为 " + num2);
var result = num1 > num2;
console.log("num1 > num2 的结果为 " + result);
result = num1 < num2;
console.log("num1 < num2 的结果为 " + result);
result = num1 >= num2;
console.log("num1 >= num2 的结果为 " + result);
result = num1 <= num2;
console.log("num1 <= num2 的结果为 " + result);
result = num1 == num2;
console.log("num1 == num2 的结果为 " + result);
result = num1 != num2;
console.log("num1 != num2 的结果为 " + result);
